server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd 
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期，true时会忽略date-format
  application:
    name: sample-service # 服务名称
  devtools:
    livereload:
      port: 35727 # 默认是35729，如果开发环境中运行多个项目都用devtools，这个端口会冲突，需要改成不同的
  sleuth:      #日志收集客户端
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
    cn.devmgr.springcloud.springboot.dao: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    preferIpAddress: true


management:
  endpoint:
    info:
      enabled: true
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        
      