server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    preferIpAddress: true


spring:
  application:
    name: admin-server # 服务名称
  devtools:
    livereload:
      port: 35725 # 默认是35729，如果开发环境中运行多个项目都用devtools，这个端口会冲突，需要改成不同的

logging:
  file: target/app.log
  level:
    ROOT: ERROR
    cn.devmgr: TRACE
