server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd 
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期，true时会忽略date-format
  application:
    name: gateway # 服务名称
  devtools:
    livereload:
      port: 35725 # 默认是35729，如果开发环境中运行多个项目都用devtools，这个端口会冲突，需要改成不同的
  cloud:
    gateway:
      routes:
      - id: sample_router # TODO: 这里缺少个例子
        uri: http://127.0.0.1/sampleservice/
        predicates:
        - name: Between
          args:
            datetime1: 2018-03-15T00:02:48.513+08:00[Asia/Shanghai]
            datetime2: 2018-03-15T02:02:48.516+08:00[Asia/Shanghai]
logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
    cn.devmgr.springcloud.springboot.dao: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    preferIpAddress: true


management:
  endpoint:
    info:
      enabled: true
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        
      