server:
  port: 8000

spring:
  devtools:
    livereload:
      port: 35728 # 默认是35729，如果开发环境中运行多个项目都用devtools，这个端口会冲突，需要改成不同的

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/ # 服务注册中心地址
  server:
    enableSelfPreservation: false
  instance:
    preferIpAddress: true


logging:
  level:
    cn.devmgr: TRACE
    org.springframework: WARN
  
 