server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd  
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  application:
    name: feignclient # 服务名称

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
    cn.devmgr.springcloud.springboot.dao: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    preferIpAddress: true

