server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd  
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  application:
    name: feignclient # 服务名称
  devtools:
    livereload:
      port: 35726 # 默认是35729，如果开发环境中运行多个项目都用devtools，这个端口会冲突，需要改成不同的

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
    cn.devmgr.springcloud.springboot.dao: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    preferIpAddress: true


management:
  endpoint:
    info:
      enabled: true
    beans:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        